name: Style

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
      - name: Pylint install
        run: pip install pylint
      - name: Pylint check
        run: pylint --fail-under=9 **/*.py
        working-directory: code
